# Parameters for SoftFoot Visualization
# Remember that there might be other important constants that can only be changed from the src code.

softfoot_viz:

  # Names of the joints of the softfoot
  joint_names: ["front_arch_joint", "back_arch_joint", "roll_joint"]
  # Names of the frames of the joints to get axes
  joint_frame_names: ["front_arch_link", "back_arch_link", "roll_link"]

  # The different feet
  softfoot_2:
    use_filter: false
    joint_pairs: [[0, 1], [0, 3], [1, 2]]
    joint_offset: [1.75, -1.64, 0.54]

    init_quat_0: [0.5, -0.5, -0.5, 0.5]
    init_quat_1: [1.0, 0.0, 0.0, 0.0]
    init_quat_2: [1.0, 0.0, 0.0, 0.0]
    init_quat_3: [1.0, 0.0, 0.0, 0.0]

    rot_match: [1, -1, 1]
    
  softfoot_3:
    use_filter: false
    joint_pairs: [[0, 1], [0, 3], [1, 2]]
    joint_offset: [-0.03, -0.07, 0.54]

    init_quat_0: [1.0, 0.0, 0.0, 0.0]
    init_quat_1: [1.0, 0.0, 0.0, 0.0]
    init_quat_2: [1.0, 0.0, 0.0, 0.0]
    init_quat_3: [1.0, 0.0, 0.0, 0.0]

    rot_match: [1, -1, 1]