# Parameters for SoftFoot Visualization
# Remember that there might be other important constants that can only be changed from the src code.

softfoot_viz:

  # Calibrate online
  calibrate_online: true

  # Names of the joints of the softfoot
  joint_names: ["front_arch_joint", "back_arch_joint", "roll_joint"]
  # Names of the frames of the joints to get axes
  joint_frame_names: ["front_arch_link", "back_arch_link", "roll_link"]

  # The different feet

  # Anterior left foot
  softfoot_1:
    joint_pairs: [[0, 1], [0, 3], [1, 2]]
  
  # Anterior right foot
  softfoot_2:
    joint_pairs: [[0, 1], [0, 3], [1, 2]]

  # Posterior left foot
  softfoot_3:
    joint_pairs: [[0, 1], [0, 3], [1, 2]]

  # Posterior right foot
  softfoot_4:
    joint_pairs: [[0, 1], [0, 3], [1, 2]]