# Parameters for SoftFoot Visualization
# Remember that there might be other important constants that can only be changed from the src code.

softfoot_viz:
  # Name of the robot
  robot_name: softfoot_thing